# Generated by Django 5.2.7 on 2025-10-17 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DiscordUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discord_id', models.BigIntegerField(unique=True)),
                ('username', models.CharField(max_length=255)),
                ('xp', models.IntegerField(default=0)),
                ('level', models.IntegerField(default=0)),
            ],
        ),
    ]
