# Generated by Django 5.2.7 on 2025-10-17 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kbrs_api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiscordProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discord_id', models.BigIntegerField(db_index=True, unique=True)),
                ('username', models.CharField(blank=True, default='', max_length=255)),
                ('level', models.IntegerField(default=0)),
                ('xp', models.IntegerField(default=0)),
                ('last_msg_xp_at', models.DateTimeField(blank=True, null=True)),
                ('last_react_xp_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.DeleteModel(
            name='DiscordUser',
        ),
    ]
