# Generated by Django 5.2.7 on 2025-10-17 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kbrs_api', '0002_discordprofile_delete_discorduser'),
    ]

    operations = [
        migrations.AddField(
            model_name='discordprofile',
            name='birthday_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='discordprofile',
            name='birthday_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='discordprofile',
            name='birthday_last_congrats',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='discordprofile',
            name='birthday_tz',
            field=models.CharField(default='UTC', max_length=64),
        ),
    ]
