# Generated by Django 5.2.7 on 2025-10-18 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kbrs_api', '0003_discordprofile_birthday_date_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='discordprofile',
            index=models.Index(fields=['-level', '-xp'], name='kbrs_api_di_level_68386f_idx'),
        ),
    ]
