# Generated by Django 5.2.7 on 2025-10-18 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kbrs_api', '0004_discordprofile_kbrs_api_di_level_68386f_idx'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmojiUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guild_id', models.BigIntegerField(db_index=True)),
                ('message_id', models.BigIntegerField(db_index=True)),
                ('sender_id', models.BigIntegerField(db_index=True)),
                ('key', models.CharField(db_index=True, max_length=128)),
                ('count', models.IntegerField(default=1)),
                ('created_at', models.DateTimeField(db_index=True)),
            ],
            options={
                'indexes': [models.Index(fields=['guild_id', 'sender_id', 'key', '-created_at'], name='kbrs_api_em_guild_i_f366c3_idx')],
            },
        ),
        migrations.CreateModel(
            name='MessageEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guild_id', models.BigIntegerField(db_index=True)),
                ('channel_id', models.BigIntegerField(db_index=True)),
                ('message_id', models.BigIntegerField(unique=True)),
                ('author_id', models.BigIntegerField(db_index=True)),
                ('words', models.IntegerField(default=0)),
                ('chars', models.IntegerField(default=0)),
                ('has_attach', models.BooleanField(default=False)),
                ('has_sticker', models.BooleanField(default=False)),
                ('is_reply', models.BooleanField(default=False)),
                ('emoji_count', models.IntegerField(default=0)),
                ('link_count', models.IntegerField(default=0)),
                ('mention_cnt', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(db_index=True)),
            ],
            options={
                'indexes': [models.Index(fields=['guild_id', 'author_id', '-created_at'], name='kbrs_api_me_guild_i_900f87_idx'), models.Index(fields=['guild_id', 'channel_id', '-created_at'], name='kbrs_api_me_guild_i_9e7501_idx')],
            },
        ),
        migrations.CreateModel(
            name='ReactionEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guild_id', models.BigIntegerField(db_index=True)),
                ('channel_id', models.BigIntegerField(db_index=True)),
                ('message_id', models.BigIntegerField(db_index=True)),
                ('reactor_id', models.BigIntegerField(db_index=True)),
                ('author_id', models.BigIntegerField(blank=True, db_index=True, null=True)),
                ('emoji_key', models.CharField(db_index=True, max_length=128)),
                ('created_at', models.DateTimeField(db_index=True)),
            ],
            options={
                'indexes': [models.Index(fields=['guild_id', 'reactor_id', '-created_at'], name='kbrs_api_re_guild_i_a5e189_idx'), models.Index(fields=['guild_id', 'emoji_key', '-created_at'], name='kbrs_api_re_guild_i_145255_idx')],
            },
        ),
        migrations.CreateModel(
            name='XpTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guild_id', models.BigIntegerField(db_index=True)),
                ('user_id', models.BigIntegerField(db_index=True)),
                ('source', models.CharField(max_length=32)),
                ('amount', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('level_before', models.IntegerField(blank=True, null=True)),
                ('xp_before', models.IntegerField(blank=True, null=True)),
                ('level_after', models.IntegerField(blank=True, null=True)),
                ('xp_after', models.IntegerField(blank=True, null=True)),
                ('leveled_up', models.BooleanField(default=False)),
            ],
            options={
                'indexes': [models.Index(fields=['guild_id', 'user_id', '-created_at'], name='kbrs_api_xp_guild_i_8edf42_idx')],
            },
        ),
    ]
