# Generated by Django 5.2.7 on 2025-10-18 21:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kbrs_api', '0005_emojiusage_messageevent_reactionevent_xptransaction'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='xptransaction',
            name='kbrs_api_xp_guild_i_8edf42_idx',
        ),
        migrations.RemoveField(
            model_name='xptransaction',
            name='level_after',
        ),
        migrations.RemoveField(
            model_name='xptransaction',
            name='level_before',
        ),
        migrations.RemoveField(
            model_name='xptransaction',
            name='leveled_up',
        ),
        migrations.RemoveField(
            model_name='xptransaction',
            name='user_id',
        ),
        migrations.RemoveField(
            model_name='xptransaction',
            name='xp_after',
        ),
        migrations.RemoveField(
            model_name='xptransaction',
            name='xp_before',
        ),
        migrations.AddField(
            model_name='xptransaction',
            name='user',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='xp_tx', to='kbrs_api.discordprofile'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='xptransaction',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='xptransaction',
            name='guild_id',
            field=models.BigIntegerField(blank=True, db_index=True, null=True),
        ),
        migrations.AddIndex(
            model_name='xptransaction',
            index=models.Index(fields=['user', '-created_at'], name='kbrs_api_xp_user_id_228745_idx'),
        ),
        migrations.AddIndex(
            model_name='xptransaction',
            index=models.Index(fields=['guild_id', '-created_at'], name='kbrs_api_xp_guild_i_180835_idx'),
        ),
        migrations.AlterModelTable(
            name='xptransaction',
            table='kbrs_api_xptransaction',
        ),
    ]
