# Generated by Django 5.2.7 on 2025-10-18 21:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kbrs_api', '0006_remove_xptransaction_kbrs_api_xp_guild_i_8edf42_idx_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='xptransaction',
            name='kbrs_api_xp_user_id_228745_idx',
        ),
        migrations.RemoveIndex(
            model_name='xptransaction',
            name='kbrs_api_xp_guild_i_180835_idx',
        ),
        migrations.AlterField(
            model_name='xptransaction',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='xp_tx', to='kbrs_api.discordprofile'),
        ),
        migrations.AlterModelTable(
            name='xptransaction',
            table=None,
        ),
    ]
