# Generated by Django 5.2.7 on 2025-11-07 18:03

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kbrs_api', '0007_remove_xptransaction_kbrs_api_xp_user_id_228745_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Achievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(db_index=True, help_text="Unique identifier for this achievement (e.g., 'first_message')", max_length=100, unique=True)),
                ('name', models.CharField(help_text='Display name', max_length=200)),
                ('description', models.TextField(help_text='What the user needs to do')),
                ('icon', models.CharField(default='🏆', help_text='Emoji icon for this achievement', max_length=50)),
                ('rarity', models.CharField(choices=[('common', 'Common'), ('rare', 'Rare'), ('epic', 'Epic'), ('legendary', 'Legendary')], default='common', max_length=20)),
                ('condition_type', models.CharField(choices=[('message_count', 'Total Messages Sent'), ('reaction_count', 'Total Reactions Given'), ('emoji_usage', 'Unique Emojis Used'), ('level_reached', 'Level Reached'), ('join_server', 'Join Server'), ('days_active', 'Days Active on Server'), ('voice_minutes', 'Voice Channel Minutes'), ('birthday_set', 'Birthday Set'), ('help_reactions', 'Help Reactions Given'), ('consecutive_days', 'Consecutive Days Active'), ('top_rank', 'Reach Top N in Leaderboard')], help_text='What metric to check', max_length=50)),
                ('condition_value', models.IntegerField(help_text="Target value (e.g., 100 for '100 messages')", validators=[django.core.validators.MinValueValidator(0)])),
                ('xp_reward', models.IntegerField(default=0, help_text='XP awarded when unlocked', validators=[django.core.validators.MinValueValidator(0)])),
                ('enabled', models.BooleanField(default=True)),
                ('hidden', models.BooleanField(default=False, help_text='Hidden achievements (surprises)')),
                ('order', models.IntegerField(default=0, help_text='Display order')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['order', 'name'],
                'indexes': [models.Index(fields=['enabled', 'condition_type'], name='kbrs_api_ac_enabled_c6641b_idx'), models.Index(fields=['rarity'], name='kbrs_api_ac_rarity_a1b7b6_idx')],
            },
        ),
        migrations.CreateModel(
            name='AchievementCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('icon', models.CharField(default='📁', max_length=50)),
                ('order', models.IntegerField(default=0)),
                ('achievements', models.ManyToManyField(blank=True, related_name='categories', to='kbrs_api.achievement')),
            ],
            options={
                'verbose_name_plural': 'Achievement Categories',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='UserAchievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('progress', models.IntegerField(default=0, help_text='Current progress towards this achievement')),
                ('unlocked', models.BooleanField(db_index=True, default=False)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('unlocked_at', models.DateTimeField(blank=True, null=True)),
                ('notified_at', models.DateTimeField(blank=True, help_text='When user was notified in Discord', null=True)),
                ('achievement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unlocks', to='kbrs_api.achievement')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='achievements', to='kbrs_api.discordprofile')),
            ],
            options={
                'indexes': [models.Index(fields=['unlocked', 'notified_at'], name='kbrs_api_us_unlocke_2f8ea7_idx'), models.Index(fields=['profile', 'unlocked'], name='kbrs_api_us_profile_8c3f63_idx')],
                'unique_together': {('profile', 'achievement')},
            },
        ),
    ]
