# Generated by Django 5.2.7 on 2025-11-07 18:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kbrs_api', '0008_achievement_achievementcategory_userachievement'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='achievementcategory',
            name='achievements',
        ),
        migrations.AddField(
            model_name='achievement',
            name='category',
            field=models.ForeignKey(blank=True, help_text='Achievement category', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='achievements', to='kbrs_api.achievementcategory'),
        ),
        migrations.AlterField(
            model_name='achievement',
            name='rarity',
            field=models.CharField(choices=[('common', 'Common'), ('uncommon', 'Uncommon'), ('rare', 'Rare'), ('epic', 'Epic'), ('legendary', 'Legendary'), ('mythic', 'Mythic')], default='common', max_length=20),
        ),
    ]
